"""Add Store model

Revision ID: d5486dedb3ec
Revises: 4b38fb11165c
Create Date: 2025-04-20 03:55:02.596240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5486dedb3ec'
down_revision = '4b38fb11165c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_image', sa.String(), nullable=True),
    sa.Column('store_review', sa.Float(), nullable=False),
    sa.Column('store_location_longitude', sa.Float(), nullable=False),
    sa.Column('store_location_latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###
