"""empty message

Revision ID: d7032af00e27
Revises: 4b783b5a6961
Create Date: 2025-03-12 23:33:34.293780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7032af00e27'
down_revision = '4b783b5a6961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
